### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Denke91** [AliceMousie/Archipelago#4]
### What happened?

I am currently hosting an async with 11 crystal players. We have encountered several findings so far, which I will be documenting here :)
In trainersanity we had some NPCs not sending checks, or only, if you talk to them from a certain direction.
Kimono Girl
![Kimono Girl ](https://github.com/AliceMousie/Archipelago/assets/1668882/f6d00964-5d09-46cd-b348-c80b2d8ca684)
Radio Tower 3F - Grunt 2
![Radio Tower floor 3](https://github.com/AliceMousie/Archipelago/assets/1668882/dca2bda9-099d-4c41-b710-914260f3a583)

### What were the expected results?

To get the check from all sides 

### Software

While playing

**Comment by Denke91** [comment]
I have even a check not sending from either side.
Ruins of Alph - Psychic Nathan
![image](https://github.com/AliceMousie/Archipelago/assets/1668882/a4068116-2db7-4dab-bcb5-ac61048927a2)

**Comment by palex00** [comment]
This should be solved in 2.0.3 if you want to close this issue

**Comment by AliceMousie** [comment]
Closing presumed fixed
