### ISSUE TITLE
Bug: Trade evolution items cannot be used

### ISSUE THREAD

**Issue by HummingHermano** [AliceMousie/Archipelago#5]
### What happened?

Trade evolution items (King's Rock, Dragon Scale, Metal Coat, Up-grade) don't have a "Use" option when selected in the pack.

![Screenshot_20240602_165537](https://github.com/AliceMousie/Archipelago/assets/9499575/0141c73f-57b8-4da9-86ec-39b392c42c9b)

Software version:
- Apworld: Beta 2.0.2
- Archipelago: 0.4.6
- BizHawk: 2.9.1

Thank you for your hard work!

### What were the expected results?

According to the beta 2.0.0 version changelog, trade evolution items could be used as if they were evolution stones.

### Software

While playing

**Comment by AliceMousie** [comment]
Fixed in 2.1.0
