### ISSUE TITLE
Bug: Fuchsia City Gym Trainers Trainersanity

### ISSUE THREAD

**Issue by vicendithas** [AliceMousie/Archipelago#8]
### What happened?

The Fuchsia City Gym trainers don't seem to be included in Trainersanity.

### What were the expected results?

Each of the Fuchsia City Gym trainers would also give an item check when Trainersanity is on.

### Software

While playing

**Comment by vicendithas** [comment]
I am playing with Mischief Enabled, which I'm guessing is why everyone was shuffled location (including Janine), so this may have been intentional. I just figured it was worth mentioning.

**Comment by AliceMousie** [comment]
Not a bug
